const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync('index.html','utf8'),source=fs.readFileSync('app.js','utf8');
function setup(audio=true){
 const nodes={}; const node=()=>({dataset:{},style:{setProperty(){}},children:[],value:'',textContent:'',attrs:{},classes:new Set(),classList:{add(){},remove(){},toggle(){}},append(c){this.children.push(c)},replaceChildren(){this.children=[]},setAttribute(k,v){this.attrs[k]=v},querySelector(){return node()},showModal(){this.open=true},close(){this.open=false},pause(){},focus(){}});
 for(const m of html.matchAll(/id="([^"]+)"/g)) nodes[m[1]]=node();
 const groups={}; for(const m of html.matchAll(/<button[^>]*data-(screen|care|tab|trick)="([^"]+)"/g)){const key=m[1],e=node();e.dataset[key]=m[2];(groups[key]??=[]).push(e)}
 let saved,oscillators=0,stops=0;
 class Audio { constructor(src){this.src=src} play(){assert(fs.existsSync(this.src),this.src);oscillators++;return Promise.resolve()} pause(){stops++} }
 const context={window:audio?{Audio}:{},navigator:{language:'en'},document:{body:node(),getElementById:id=>{assert(nodes[id],id);return nodes[id]},querySelector:()=>node(),querySelectorAll:q=>groups[q.match(/data-(\w+)/)?.[1]]||[],createElement:node,addEventListener(){}},localStorage:{getItem:()=>null,setItem:(k,v)=>saved=v},setTimeout:()=>1,clearTimeout(){},setInterval(){},console};vm.createContext(context);vm.runInContext(source,context);
 return {context,nodes,groups,get saved(){return JSON.parse(saved)},get sounds(){return oscillators},get stops(){return stops},exec:s=>vm.runInContext(s,context)};
}
const run=Number(process.argv[2]);let count=0;function check(value,label){assert(value,label);count++;console.log('PASS',label)}
if(run===1){const t=setup();check(t.groups.screen.map(x=>x.dataset.screen).join(',')==='care,chat','Only Pet and Talk in main navigation');check(t.groups.tab.map(x=>x.dataset.tab).join(',')==='outfits,colors','Style has only clothing and colors');t.groups.care.find(x=>x.dataset.care==='play').onclick();check(t.context.document.body.dataset.screen==='play','Pet Play action directly opens tricks');check(t.groups.trick.length===3,'Hop, Twirl and Dance directly available');t.groups.trick[0].onclick();check(t.saved.care.play&&t.saved.streak.count===1,'Trick counts as daily play and care streak');t.groups.screen.find(x=>x.dataset.screen==='chat').onclick();check(t.context.document.body.dataset.screen==='chat','Talk reachable in one tap');t.exec("chat('My favorite color is blue')");check(t.nodes['memory-list'].textContent.includes('blue'),'Memories belong to conversation');t.nodes['forget-memories'].onclick();check(!Object.keys(t.saved.memories).length,'Forget memories clears saved data');}
if(run===2){
 for(const file of ['eating','washing','sleeping','waking','hop','twirl','dancing']) {
  const bytes=fs.readFileSync(`public/audio/${file}.wav`);let offset=12,payload;
  while(offset+8<=bytes.length){const size=bytes.readUInt32LE(offset+4);if(bytes.toString('ascii',offset,offset+4)==='data'){payload=bytes.subarray(offset+8,offset+8+size);break}offset+=8+size+(size%2)}
  check(payload&&payload.length>2000&&payload.some(value=>value!==0),`${file} has nonempty audio samples`);
 }
 const t=setup();for(const action of ['feed','wash','sleep','wake','jump','spin','dance']){const before=t.sounds;t.exec(`activitySound('${action}')`);check(t.sounds>before,`${action} schedules activity audio`)}t.nodes.sound.onclick();const before=t.sounds;t.exec("activitySound('feed')");check(t.sounds===before&&t.stops>0,'Mute stops active effects and suppresses new ones');t.nodes.sound.onclick();t.exec("activitySound('feed')");check(t.sounds>before,'Unmute restores sound');const stopped=t.stops;t.context.window.TouStopAudio();check(t.stops>stopped,'Native background hook stops activity audio');const silent=setup(false);silent.groups.trick[0].onclick();check(silent.saved.care.play,'Game works without an audio API');}
if(run===3){const t=setup();t.exec('state.stats.energy=5');const before=t.sounds;t.groups.trick[1].onclick();check(t.sounds===before&&t.nodes.speech.textContent.includes('Rest'),'Tired pet explains how to resume play without sounding a trick');t.exec('state.stats.energy=80;state.stats.hunger=10;state.stats.cleanliness=10');t.groups.care.find(x=>x.dataset.care==='feed').onclick();check(t.saved.stats.hunger===100&&t.sounds>before,'Feeding restores hunger and plays audio');t.groups.care.find(x=>x.dataset.care==='wash').onclick();check(t.saved.stats.cleanliness===100,'Cleaning restores cleanliness');t.groups.care.find(x=>x.dataset.care==='sleep').onclick();check(t.saved.sleeping,'Rest starts sleeping');t.groups.care.find(x=>x.dataset.care==='sleep').onclick();check(!t.saved.sleeping,'Rest toggles to wake');t.groups.tab[1].onclick();check(t.nodes['tab-content'].children[0].children.length===6,'All six colors remain available');t.groups.tab[0].onclick();t.nodes['tab-content'].children[0].children[1].onclick();check(t.saved.outfit==='bow','Outfits save correctly');t.exec("chat('dance')");check(t.saved.care.play,'Voice/text trick shares daily play behavior');new vm.Script(fs.readFileSync('sw.js','utf8'));check(true,'Service worker and application syntax valid');}
console.log(`Run ${run}: ${count} checks passed`);
